# Generated by Django 2.2.1 on 2019-05-04 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOfWorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.TextField(blank=True, default=None, null=True)),
                ('fromDate', models.DateField()),
                ('fromTimeFrom', models.TimeField()),
                ('fromTimeTo', models.TimeField()),
                ('toDate', models.DateField()),
                ('toTimeFrom', models.TimeField()),
                ('toTimeTo', models.TimeField()),
                ('reason', models.CharField(max_length=100)),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('dateApproved', models.DateField(blank=True, default=None, null=True)),
                ('approvedBy', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
