# Generated by Django 2.2.1 on 2019-05-04 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profilePic', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('phoneNum', models.TextField(blank=True, default=None, null=True)),
                ('mfa_code', models.TextField(blank=True, default=None, null=True)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Undertime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFiled', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('department', models.TextField(blank=True, default=None, null=True)),
                ('date_ut', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('num_of_hrs', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('dateApproved', models.DateField(blank=True, default=None, null=True)),
                ('approvedBy', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.TextField(blank=True, default=None, null=True)),
                ('prodTool', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('reasons', models.CharField(max_length=100)),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('dateApproved', models.DateField(blank=True, default=None, null=True)),
                ('approvedBy', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('e_uname', models.CharField(max_length=100)),
                ('payslip_date', models.DateField()),
                ('payslip', models.FileField(upload_to='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFiled', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('department', models.TextField(blank=True, default=None, null=True)),
                ('date_ot', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('num_of_hrs', models.TextField()),
                ('reason', models.TextField()),
                ('project_name', models.TextField()),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('dateApproved', models.DateField(blank=True, default=None, null=True)),
                ('approvedBy', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('leaveType', models.TextField()),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('timeFrom', models.TimeField(blank=True, default=None, null=True)),
                ('timeTo', models.TimeField(blank=True, default=None, null=True)),
                ('reason', models.TextField()),
                ('status', models.TextField()),
                ('leaveCount', models.FloatField()),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('department', models.TextField(blank=True, default=None, null=True)),
                ('approvedBy', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bcast_rec', models.TextField()),
                ('bcast_subj', models.TextField()),
                ('bcast_desc', models.TextField()),
                ('bcast_image', models.ImageField(default=None, null=True, upload_to='')),
                ('bcast_file', models.FileField(default=None, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
